services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672" #Admin console access
      - "15674:15674" #rabbit_web_stomp
      - "61613:61613" # STOMP
      - "1883:1883" #MQTT
    volumes:
        - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: password
#      RABBITMQ_DEFAULT_VHOST: /
