
spring:
  application:
    name: @project.artifactId@
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    relay:
      host: ${RELAY_HOST:localhost}
      port: ${RELAY_PORT:61613}
logging:
  level:
    org:
      springframework:
        data: DEBUG
        web: DEBUG
        security: DEBUG
        amqp: DEBUG